### ISSUE TITLE
Environment variables are not read correctly

### ISSUE THREAD

**Issue by benjay10** [benjay10/delta-notifier-strict#3]
When you supply an environment variable through docker-compose such as:

    `DEBUG_DELTA_SEND: "true"`

the action of debugging the sending of delta messages is always done, irrespective of the boolean value supplied. So specifying "false" also counts as a truthy value. This is due to the way these values are tested in the code: with an `if (process.env['DEBUG_DELTA_SEND'])`.

The environment variable should only be read as truthy when the value is "true", or maybe also as "1".

**Comment by nvdk** [comment]
consider using `env-var`, see https://github.com/lblod/mu-auth-sudo/blob/5adb4acaabc4fe287b13f06d86d22447337f6a9f/src/auth-sudo.js#L3 for an example
